name: Build public pages

on:
  push:
    tags:
     - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Build
      run: |
        npm install
        npm run-script build
    - name: Publish
      run: |
        npm run-script deploy
